### ISSUE TITLE
Question regarding target format

### ISSUE THREAD

**Issue by scudette** [EricZimmerman/KapeFiles#1038]
Hi Kapefiles maintainers,

I am trying to understand the exact specification of the Kapefiles Targets as described https://ericzimmerman.github.io/KapeDocs/#!Pages\2.1-Targets.md#path

This is specifically in context of the following target

https://github.com/EricZimmerman/KapeFiles/blob/master/Targets/Windows/AppCompatPCA.tkape

```yaml
Targets:
    -
        Name: AppCompat PCA Folder
        Category: ApplicationCompatibility
        Path: C:\Windows\appcompat\pca
```

The target points at a directory but does not have recursive = true set. According to the documentation Path should point at the files to acquire and recursive = true should be set to imply this is a directory.

In Velociraptor we convert the targets to globs (which are much simpler and unambiguous). So when recursive = true we add a `**` glob to the end of the path, otherwise we assume the target refers to a file. For example in the following targets https://github.com/EricZimmerman/KapeFiles/blob/master/Targets/Antivirus/AVG.tkape

```yaml
    -
        Name: AVG FileInfo DB
        Category: Antivirus
        Path: C:\ProgramData\AVG\Antivirus
        FileMask: FileInfo2.db
        Recursive: true
    -
        Name: AVG lsdbj2 JSON
        Category: Antivirus
        Path: C:\ProgramData\AVG\Antivirus
        FileMask: lsdb2.json
```

We add a glob like `C:\ProgramData\AVG\Antivirus\**\*.FileInfo2.db` for the first one and `C:\ProgramData\AVG\Antivirus\lsdb2.json` for the second.

So in the above PCA example we produce a glob like `C:\Windows\appcompat\pca` which does not work because pca is actually a directory.

So the question is - what does Path actually mean here? The docs say:

> Path: The path to the file to be collected. 
> Recursive: When true, will recursively copy everything from Path. 

Implies path should be a path to a file and not a directory - and if it is a directory recursive should be stated. Also the docs say:

> While not required, for consistency, all directory names should end with a backslash to make it clear path denotes a directory.

So this is very confusing - how should we interpret the PCA target?

I just wanted to ask here is there an implied rule that if `path` is a directory recursive is implied? This can obviously only be determined at runtime so will require a major refactor of the conversion script. It would also imply that recursive is completely redundant (since you can not really recurse into a file so anytime a target specifies a directory it implies its recursive).

This is the only way I can imagine the PCA target can actually work.
