### ISSUE TITLE
Allow the use of mvars in the output filename

### ISSUE THREAD

**Issue by Karneades** [EricZimmerman/KapeFiles#384]
**KAPE version**
0.9.6

**Is your feature request related to a problem? Please describe.**
I created a module for RegRipper for which the analyst can supply a module variable to specify the plugin which should be used.

See https://github.com/Karneades/KapeFiles/blob/addNtuserVariable/Modules/Registry/RegRipper-ntuser-variable.mkape (I will make a PR asap if of need to others and after the output filename can include the plugin name).

```
ExportFormat: txt
FileMask: ntuser.dat
Processors:
    -
        Executable: regripper\rip.exe
        CommandLine: -r %sourceFile% -p %ntuserPlugin%
        ExportFormat: txt
        ExportFile: regripper-ntuser-%ntuserPlugin%.txt
        Append: true
```

The variable is only expanded in the command line but not in the output filename.

**Describe the solution you'd like**
Allow the use of the variable name also in the output. It would allow the awesome tool handling from KAPE to use specific plugins from RR for analysis.

**Describe alternatives you've considered**

It could be defined that no variable names should be expanded in other places than the cl (e.g. because the effort to implement it doesn't match with the seldom use of it). It's ready implicitly stated in https://github.com/EricZimmerman/KapeDocs/blob/master/Pages/3.-Using-KAPE.md#mvars that the variables are expanded in the command line. 

**Additional context**
N/A

**Comment by Karneades** [comment]
@EricZimmerman should that work using mvars inside other places than the command line?

**Comment by EricZimmerman** [comment]
have to think thru this.

what happens if the variable is not supplied, do i just use the variable name in the output?

Example

ExportFile: regripper-ntuser-%ntuserPlugin%.txt

what if you do not supply %ntuserPlugin% ?

would i just name the file

regripper-ntuser-ntuserPlugin.txt

or leave it 

regripper-ntuser-%ntuserPlugin%.txt

probably the latter.

the bigger problem here is going to the the command line in that it will fail without the right variables, but in reality, that isnt MY problem per se.

Thoughts?

**Comment by Karneades** [comment]
> what happens if the variable is not supplied, do i just use the variable name in the output?

I would handle it like with the command line params, if unset, then use the whole string, e.g. regripper-ntuser-%ntuserPlugin%.txt. this is also the case in modules if a variable is unset, then the parameter as it is is provided to the cli.

> the bigger problem here is going to the the command line in that it will fail without the right variables, but in reality, that isnt MY problem per se.

same with normal module variables, if unset, then the command line gets the variable with the % around the variable name.

**Comment by EricZimmerman** [comment]
k, that was how i was leaning.

**Comment by EricZimmerman** [comment]
OK i think this is done
[kape99Beta.zip](https://github.com/EricZimmerman/KapeFiles/files/5919359/kape99Beta.zip)

```
Processors:
    -
        Executable: regripper\rip.exe
        CommandLine: -r %sourceFile% -f ntuser
        ExportFormat: txt
        ExportFile: regripper-ntuser-%ntuserPlugin%.txt
```


.\kape.exe --msource C:\Temp\ --mdest C:\Temp\mout --module RegRipper-ntuser --mflush

results in a file named:

**regripper-ntuser-%ntuserPlugin%.txt**

.\kape.exe --msource C:\Temp\ --mdest C:\Temp\mout --module RegRipper-ntuser --mflush --mvars **ntuserPlugin:Eric**

results in a file named:

regripper-ntuser-**Eric**.txt

.\kape.exe --msource C:\Temp\ --mdest C:\Temp\mout --module RegRipper-ntuser --mflush --mvars **ntuserPlugin1**:Eric

results in a file named 

regripper-ntuser-%ntuserPlugin%.txt


here is a test build. updated nuget stuff and this feature. please test
