### ISSUE TITLE
Chainsaw issue

### ISSUE THREAD

**Issue by gs3cl** [EricZimmerman/KapeFiles#558]
Hey,

**KAPE version**
1.1.0.0

**Describe the bug**

1. Chainsaw module is not working due to missing folder with eventlogs
2. json output is not working due to missing file extension (--json <json-output> -> see chainsaw documentation)

**To Reproduce**

1. run KAPE with:
````
.\kape.exe --tsource C: --tdest G:\TriageOutput\KAPE\tout --tflush --target EventLogs --vss --mdest G:\TriageOutput\KAPE\mout --mflush --module Chainsaw --debug --gui
````

**result:**

error:  [!] Chainsaw exited: An error occurred while trying to deserialize evtx stream.

```
By F-Secure Countercept (@FranticTyping, @AlexKornitzer)
[+] Found 324 EVTX files
[+] Converting detection rules...
[+] Loaded 1166 detection rules (278 were not loaded)
[+] Saving results to CSV files
                [!] Chainsaw exited: An error occurred while trying to deserialize evtx stream.
Executed 1 processor in 13,7789 seconds
```

```
Executing remaining modules...
        Running 'Chainsaw\Chainsaw.exe': hunt --rules "D:\FORENSICS\KAPE\Modules\bin\chainsaw\sigma_rules" --mapping "D:\FORENSICS\KAPE\Modules\bin\chainsaw\mapping_files\sigma-mapping.yml" --csv --lateral-all --full G:\TriageOutput\KAPE\tout
```

I think the issue is in the last Part: **--full G:\TriageOutput\KAPE\tout** Chainsaw is not able to find the eventlogs therefore can't execute the module

**Working solution**
- use `%sourceDirectory%\C\Windows\System32\winevt\logs` instead of `%sourceDirectory%`
- add a file after --json option -> `--json output.json`

chainsaw.mkape

```
Description: Chainsaw - Rapidly Search and Hunt through Windows Event Logs
Category: EventLogs
Author: Andrew Rathbun, Georg Lauenstein
Version: 1.3
Id: 30bb22d0-ebd3-4e9e-9e1c-c6db90454430
BinaryUrl: https://github.com/countercept/chainsaw
ExportFormat: csv
Processors:
    -
        Executable: Chainsaw\Chainsaw.exe
        CommandLine: hunt "%sourceDirectory%\C\Windows\System32\winevt\logs" --rules "%kapeDirectory%\Modules\bin\chainsaw\sigma_rules" --mapping "%kapeDirectory%\Modules\bin\chainsaw\mapping_files\sigma-mapping.yml" --csv --lateral-all --full
        ExportFormat: csv
    -
        Executable: Chainsaw\Chainsaw.exe
        CommandLine: hunt "%sourceDirectory%\C\Windows\System32\winevt\logs" --rules "%kapeDirectory%\Modules\bin\chainsaw\sigma_rules" --mapping "%kapeDirectory%\Modules\bin\chainsaw\mapping_files\sigma-mapping.yml" --json output.json --lateral-all --full
        ExportFormat: json
# Documentation
# https://github.com/countercept/chainsaw
# As of 1.02, Chainsaw does not allow for outputting to a different directory other than where Chainsaw.exe resides, which should be .\KAPE\Modules\bin\chainsaw\Chainsaw.exe
# Version 1.1+ of this Module ensures the Sigma rules located in .\KAPE\Modules\bin\chainsaw\sigma_rules are loaded and used during the scan.
# https://github.com/SigmaHQ/sigma/tree/master/rules/windows has a lot of Sigma rules that appear to be included with Chainsaw
```

**Results after Working solution:**

see attached files

Regards,

[2021-10-21T163843_ConsoleLog_ChainsawTestingJSONoutput.txt](https://github.com/EricZimmerman/KapeFiles/files/7391509/2021-10-21T163843_ConsoleLog_ChainsawTestingJSONoutput.txt)
[2021-10-21T154640_ConsoleLog_chainsawTesting.txt](https://github.com/EricZimmerman/KapeFiles/files/7391510/2021-10-21T154640_ConsoleLog_chainsawTesting.txt)
![2021-10-21 18_42_24-Chainsaw](https://user-images.githubusercontent.com/89155053/138322119-6637826a-9476-43ef-ad60-383844d0a0f1.png)
