### ISSUE TITLE
YAML syntax question

### ISSUE THREAD

**Issue by Banaanhangwagen** [EricZimmerman/KapeFiles#59]
I am trying to make a new module, but I get a syntax error. Maybe you guys can point me in the right direction.

The module is for recovering NTLM hashes with mimikatz

In `cmd` the correct command is: (note that the double quote is mandatory in order to consider the command as one)
```
mimikatz.exe "lsadump::sam /system:path\to\SYSTEM /sam:path\to\SAM"
```

I wrote this in the module:
```
Processors:
    -
        Executable: path\to\Modules\bin\mimikatz.exe
        CommandLine: "lsadump::sam /system:%sourceDirectory%\SYSTEM /sam:%sourceDirectory%\SAM"
        ExportFormat: txt
```
It gives the following error for the `double quote`
```
(Line: 11, Col: 22, Idx: 309) - (Line: 11, Col: 61, Idx: 348): While parsing a quoted scalar, find unknown escape character.
```

Is there a way to escape this?
Omitting the double quote is not an option, while mimikatz will interpret this as three separate commands.

I found a solution by cheating, namely adding another command with `-`in front of it; example `-version`, but that's not cool because mimikatz gives an error for not recognizing it, but `lsadump` works correctly
```
Processors:
    -
        Executable: path\to\Modules\bin\mimikatz.exe
        CommandLine: -version "lsadump::sam /system:%sourceDirectory%\SYSTEM /sam:%sourceDirectory%\SAM"
        ExportFormat: txt
```
