### ISSUE TITLE
Kape not expanding target Paths

### ISSUE THREAD

**Issue by mcvic1rj** [EricZimmerman/KapeFiles#664]
**KAPE version**

v1.2.0.0 and v1.1.0.1

**System Information**
VMware Fusion VM running Windows 10 Education build 19044

**Describe the bug**

Kape Does not appear to be expanding wildcards in a targets Path parameter. Based on ProcMon, Kape does not appear to even query for the directory.

**To Reproduce**
Using a pared down version of the TeamViewer target with the command `.\kape.exe --tsource C --tdest c:\kapes\ --tflush --target TeamViewerLogs --debug --gui`

```yaml
Description: TeamViewer Logs
Author: Hadar Yudovich
Version: 1.1
Id: 6f2cd531-1f4b-4f0b-aa96-2426621b0a14
RecreateDirectories: true
Targets:
    -
        Name: TeamViewer Application Logs wildcard
        Category: ApplicationLogs
        Path: C:\Program Files*\TeamViewer\
        FileMask: 'TeamViewer*_Logfile*'
        Comment: "Includes TeamViewer<version>_Logfile.log and TeamViewer<version>_Logfile_OLD.log"
```

**Expected behavior**

Expansion of the `Path` parameter to include `C:\Program Files\` and `C:\Program Files (x86)\` 

**Screenshots**

<img width="1153" alt="image" src="https://user-images.githubusercontent.com/10363041/178005689-5e5736a3-f580-468a-a304-339552c4bf4a.png">

**Additional context**
This does not appear to happen with other folders/paths like `C:\Users\*\`

Switching the path to `C:\Program File*\TeamViewer\` to possibly rule out an expansion issue results in the same issue.
