### ISSUE TITLE
Unicode/Nulls in Output - Autoruns & eventually others

### ISSUE THREAD

**Issue by piesecurity** [EricZimmerman/KapeFiles#72]
The exact same issue as https://github.com/EricZimmerman/KapeFiles/issues/5

Autorunsc v13.94 presents very odd characters when executing with KAPE. The output has Null characters and word wraps in odd locations. Regardless of the export format chosen or the command line options are given, the output is garbled. Running Kape from command prompt, CMDER, or Powershell doesn't change the results

![image](https://user-images.githubusercontent.com/15093016/57822887-7c286300-7763-11e9-8866-2590f0e13f3e.png)

![image](https://user-images.githubusercontent.com/15093016/57822939-b85bc380-7763-11e9-806d-544fa7f378dd.png)

I recall seeing this problem trying to use Out-File when scripting with Powershell V2. I suspect the same underlying .NET Framework calls are affecting how Kape handles the output. I'm sure other utilities will have issues in the future aside from Density Scout and Autoruns.

**Short Term Work Around**
In the .mkape file can wrap Powershell and redirect the output with Set-Content.

```
BinaryUrl: https://download.sysinternals.com/files/Autoruns.zip
ExportFormat: txt
Processors:
    -
        Executable: C:\Windows\system32\WindowsPowerShell\v1.0\powershell.exe
        CommandLine: -command "autorunsc.exe * -accepteula -c -s| set-content c:\temp\Autoruns.txt"
        ExportFormat: txt
        ExportFile: autoruns.txt
```
Not ideal as it would be good to leverage the export formats built into Kape to modify the autoruns command

![image](https://user-images.githubusercontent.com/15093016/57823380-38cef400-7765-11e9-824c-90acb4e44175.png)
