### ISSUE TITLE
Enhancement: architecture specific executables in modules

### ISSUE THREAD

**Issue by ecapuano** [EricZimmerman/KapeFiles#79]
A few of the binaries I'm trying to build into KAPE modules have x86 and x64 variants. Would typically have to wrap these in a PowerShell script to detect architecture.

Would be awesome if there was a way to specify both versions of an Executable in a module and let KAPE pick the best one...

Perhaps `Executable` can be the default in all situations but if an x86 binary is provided and it is an x86 system, prefer the x86 executable.

example:
```
Processors:
    -
        Executable: my-binary-x64.exe
        Executable_x86: my-binary-x86.exe
```
