### ISSUE TITLE
2 Features for kape targets 

### ISSUE THREAD

**Issue by SolitudePy** [EricZimmerman/KapeFiles#888]
**KAPE version**
latest

**Is your feature request related to a problem? Please describe.**
WhatsApp.tkape for example

**Describe the solution you'd like**
Feature 1)
Path variable in the tkape files should have a wildcard option to match a directory, Example:
C:\Program Files\*SomeApp*

Feature 2)
SaveAsFileName variable in the tkape files should have a %destinationFileName% parameter similar to the mkape parameters so the target filename can be altered, Example:
SaveAsFileName: %destinationFileName%.jpg

**Describe alternatives you've considered**
Would like to know of any.

**Additional context**
An example can be seen in the PR https://github.com/EricZimmerman/KapeFiles/pull/887: 

Feature 1)
WhatsApp.tkape could be better addressed with using the following path instead:
C:\Users\%user%\AppData\Local\Packages\*WhatsAppDesktop*\LocalCache\Roaming\WhatsApp\Cache

Feature 2)
WhatsApp_Media.tkape could be better addressed renaming the target files with a .jpg extension to make them readable:
Path: C:\Users\%user%\AppData\Local\Packages\5319275A.WhatsAppDesktop_cv1g1gvanyjgm\LocalState\profilePictures
SaveAsFileName: %destinationFileName%.jpg

**Comment by SolitudePy** [comment]
1 is not supported from my testing

**Comment by EricZimmerman** [comment]
Hmm. I know wild cards in between separators works

**Comment by SolitudePy** [comment]
Well wild C:\Program Files\\*\\ will catch any folder under Program Files but if you want to match a folder by name it would be more efficient such as C:\Program Files\\*SomeApp\*

**Comment by AndrewRathbun** [comment]
I just tested the TeamViewer Target and it worked as expected.

![image](https://github.com/EricZimmerman/KapeFiles/assets/36825567/be42061c-035c-403c-b07f-8fca38801497)


Specifically, this part:

```yaml
    -
        Name: TeamViewer Application Logs
        Category: ApplicationLogs
        Path: C:\Program Files*\TeamViewer\
        FileMask: 'TeamViewer*_Logfile*'
        Comment: "Includes TeamViewer<version>_Logfile.log and TeamViewer<version>_Logfile_OLD.log"
```

NOTE: I had to copy the file found in `Program Files`, add a few characters (so KAPE didn't SHA1 dedupe) and place it in `C:\Program Files (x86)\TeamViewer` for this test scenario. The `Program Files*` wildcard worked as expected, as did the wildcards in the FileMask.

I even went futher and added another slightly different file with a different file name to test the double wildcard in the FileMask and it worked.

![image](https://github.com/EricZimmerman/KapeFiles/assets/36825567/a3087cca-85d2-4b97-b7b8-38fe71962f9b)

I then went ANOTHER step further and modified the Target to this:

```yaml
    -
        Name: TeamViewer Application Logs
        Category: ApplicationLogs
        Path: C:\Program Files*\*eamViewe*\
        FileMask: 'TeamViewer*_Logfile*'
        Comment: "Includes TeamViewer<version>_Logfile.log and TeamViewer<version>_Logfile_OLD.log"
```

and it worked!

![image](https://github.com/EricZimmerman/KapeFiles/assets/36825567/cbb13b26-185e-43e7-825e-1faa715a48a3)
